#
# Copyright (C) 2020-2022 Texas Instruments Incorporated - https://www.ti.com/
#	Suman Anna <s-anna@ti.com>
#
# SPDX-License-Identifier:     GPL-2.0+
#

obj-y	+= am62x_var_som.o
obj-y += ../common/am62x_eeprom.o
obj-y += ../common/am62x_dram.o
